#!/bin/bash

#SBATCH --chdir /home/ardoin/

#SBATCH --nodes 1

#SBATCH --cpus-per-task 1

#SBATCH --gres=gpu:1

#SBATCH --ntasks 1

#SBATCH --account=vita

#SBATCH --mem 30G

#SBATCH --time 1:00:00

echo "fidis $HOSTNAME"

source venv1/bin/activate

python3 ~/Dial-a-Ride/generator.py \
--save_type pickle \
--size_of_images 50 \
--number_of_pixel_per_image 2 \
--size_of_data 100000 \
--unique_nn True \
--moving_car True \
--codding 2channels
